### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by Vanilla99** [VladimirSinitsin/person_reid_yolo#1]
Hello, may I ask why this file "requirements.txt" is not exist?

**Comment by VladimirSinitsin** [comment]
@Vanilla99 
Hi! 
Thank you for this issue! Of course, I forgot about this file because I use conda and for some reason I decided that `environment.yml` file would be enough. I will add `requirements.txt` soon
Regards

**Comment by VladimirSinitsin** [comment]
And here it is:
https://github.com/VladimirSinitsin/person_reid_yolo/commit/effe0bc229dc85bf27f7bf9b5dbdb5018cf97a36
Please check if everything is all right. If there are problems, please resume this issue. At this point, I'm closing it down.
